// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PETADOPCION_FINAL.Models;

#nullable disable

namespace PETADOPCION_FINAL.Migrations
{
    [DbContext(typeof(PetadopcionContext))]
    partial class PetadopcionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Adopcione", b =>
                {
                    b.Property<int>("IdAdopcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_adopcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdopcion"));

                    b.Property<DateTime?>("FechaAdopcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_adopcion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdAdoptante")
                        .HasColumnType("int")
                        .HasColumnName("id_adoptante");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    b.HasKey("IdAdopcion")
                        .HasName("PK__Adopcion__E4E156E909F1875A");

                    b.HasIndex("IdAdoptante");

                    b.HasIndex("IdMascota");

                    b.ToTable("Adopciones");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.DocumentosUsuario", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("EstadoVerificacion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_verificacion");

                    b.Property<DateTime?>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_archivo");

                    b.Property<string>("UrlFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlRecibo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UrlRecibo");

                    b.HasKey("IdDocumento")
                        .HasName("PK__Document__5D2EE7E5454B2962");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documentos_Usuario", (string)null);
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("EstadoAdopcion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Disponible")
                        .HasColumnName("estado_adopcion");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuarioPublicador")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_publicador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sexo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdMascota")
                        .HasName("PK__Mascotas__6F037352D0E195EE");

                    b.HasIndex("IdUsuarioPublicador");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.MascotaFoto", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_foto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<bool?>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_principal");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_foto");

                    b.HasKey("IdFoto")
                        .HasName("PK__Mascota___620EA3A513BE8CD2");

                    b.HasIndex("IdMascota");

                    b.ToTable("Mascota_Fotos", (string)null);
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Noticia", b =>
                {
                    b.Property<int>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNoticia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnlaceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuarioPublicador")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNoticia");

                    b.HasIndex("IdUsuarioPublicador");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__6ABCB5E07F8076EA");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.SolicitudesAdopcion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("En revisión")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    b.Property<int>("IdUsuarioSolicitante")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_solicitante");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__Solicitu__5C0C31F34F79777A");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.ToTable("Solicitudes_Adopcion", (string)null);
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__4E3E04AD09D5D372");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__AB6E61643ED7EC1F")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Adopcione", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Usuario", "IdAdoptanteNavigation")
                        .WithMany("Adopciones")
                        .HasForeignKey("IdAdoptante")
                        .IsRequired()
                        .HasConstraintName("FK__Adopcione__id_ad__5441852A");

                    b.HasOne("PETADOPCION_FINAL.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("Adopciones")
                        .HasForeignKey("IdMascota")
                        .IsRequired()
                        .HasConstraintName("FK__Adopcione__id_ma__534D60F1");

                    b.Navigation("IdAdoptanteNavigation");

                    b.Navigation("IdMascotaNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.DocumentosUsuario", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("DocumentosUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__id_us__4F7CD00D");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Mascota", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Usuario", "IdUsuarioPublicadorNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdUsuarioPublicador")
                        .IsRequired()
                        .HasConstraintName("FK__Mascotas__id_usu__412EB0B6");

                    b.Navigation("IdUsuarioPublicadorNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.MascotaFoto", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("MascotaFotos")
                        .HasForeignKey("IdMascota")
                        .IsRequired()
                        .HasConstraintName("FK__Mascota_F__id_ma__44FF419A");

                    b.Navigation("IdMascotaNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Noticia", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioPublicador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.SolicitudesAdopcion", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("SolicitudesAdopcions")
                        .HasForeignKey("IdMascota")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitud__id_ma__49C3F6B7");

                    b.HasOne("PETADOPCION_FINAL.Models.Usuario", "IdUsuarioSolicitanteNavigation")
                        .WithMany("SolicitudesAdopcions")
                        .HasForeignKey("IdUsuarioSolicitante")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitud__id_us__4AB81AF0");

                    b.Navigation("IdMascotaNavigation");

                    b.Navigation("IdUsuarioSolicitanteNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Usuario", b =>
                {
                    b.HasOne("PETADOPCION_FINAL.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__id_rol__3C69FB99");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Mascota", b =>
                {
                    b.Navigation("Adopciones");

                    b.Navigation("MascotaFotos");

                    b.Navigation("SolicitudesAdopcions");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PETADOPCION_FINAL.Models.Usuario", b =>
                {
                    b.Navigation("Adopciones");

                    b.Navigation("DocumentosUsuarios");

                    b.Navigation("Mascota");

                    b.Navigation("SolicitudesAdopcions");
                });
#pragma warning restore 612, 618
        }
    }
}
